### PR TITLE
Add LEDs

### LINKED ISSUE #10: Add LEDs

### PR DESCRIPTION
**Pull request by dbrgn**
Red, Yellow, Green.

Open questions:

- Do we want R/Y/G LEDs, or maybe some other colors?
- Do we need PWM capability? If yes, will those pins (PA7/PB0/PB1) support PWM?
- Should we label the LEDs on the PCB with a function, or should we just call them LED[123] to be more flexible?

Fixes #10.

### CODE REVIEW

**Comment by dbrgn** [comment]
> Do we need PWM capability? If yes, will those pins (PA7/PB0/PB1) support PWM?

All those pins have timer functionality, so, yes.

**Comment by rnestler** [comment]
> Do we want R/Y/G LEDs, or maybe some other colors?

Are blue LEDs still cool? :wink:

**Comment by rnestler** [comment]
The IO's can only deliver a maximum of 16mA so we need higher LED resistors.

**Comment by rnestler** [comment]
Reset states are all also OK: High impedance input -> no lights on on boot.

**Comment by dbrgn** [comment]
I limited the current to 10 mA with the latest commit.

Let's stick to LED numbers for now.

**Pull request merged**
